DRAFT: Initial support for apiv2
chanzuckerberg/cryoet-data-portal pull request #1085
Opened 2024-08-29 21:29 UTC by jgadling

This is a checkpoint: Basic relationships and filters work, but I haven't had a chance to test all of the filter operators and update test infra yet.

2024-09-03 21:21 UTC, andy-sweet reviewed
Generally looks good, and I'm happy that the codegen module didn't need to be changed much.

After setting up an [v2 backend](https://github.com/chanzuckerberg/cryoet-data-portal-backend/tree/main/apiv2), I was able to run some quick manual tests, so agreed this seems to be kinda working. Lots of the list relationships give empty lists, but that could just be due to the local test infra fakes.

With the new version of the backend, can we specify comments/descriptions on the item/list relationships? That was not possible with hasura, so I just had to autogenerate those descriptions with sometimes awkward results (e.g. ` The alignment this per section alignment parameters is a part of`).

2024-10-18 00:24 UTC, uermel requested changes

2024-10-18 00:24 UTC, uermel commented on client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py
> +        return strcase.to_lower_camel(self.__name)
This seems to cause an exception in `strcase`, as `self.__name` is a list, not a string. 

to reproduce: 
```python
import cryoet_data_portal as cdp

client = cdp.Client()
point_annos = cdp.AnnotationFile.find(
    client,
    [
        cdp.AnnotationFile.tomogram_voxel_spacing.run_id == 1000,
        cdp.AnnotationFile.annotation_shape.shape_type._in(["Point", "OrientedPoint"]),  # noqa
    ],
)
```

`TypeError: expected string or bytes-like object`

2024-10-18 00:24 UTC, uermel commented on client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py
> +        return strcase.to_lower_camel(self.__name)
Fix seems to be as easy as 

```python
return [strcase.to_lower_camel(n) for n in self.__name]
```

2024-10-30 15:39 UTC, uermel approved these changes

2024-10-30 20:00 UTC, merged