feat: Add empty states for annotations and tomograms tables
chanzuckerberg/cryoet-data-portal pull request #1155
Opened 2024-09-18 21:34 UTC by bchu1

#1065

2024-09-20 16:41 UTC, Janeece requested changes
thanks @bchu1, this is looking so good! 

**Here's my comments based on the video:**
- [x] Seem to be missing the space between the empty state description and the folder illustrations -- should be space-xxl in between
<img width="592" alt="Screenshot 2024-09-20 at 9 28 23 AM" src="https://github.com/user-attachments/assets/083684f4-5f4b-44a8-b3cb-1173ca89ac1d">

**These two relate to the download run data dialog, so this may not be the right ticket to fix this feedback in:**
- [ ] Low priority - In download dialog, can we have the "Download all run data" callout default to open? (seems SDS v2 fixed the bug where it was stuck open, but open is preferred) <img width="505" alt="Screenshot 2024-09-20 at 9 33 42 AM" src="https://github.com/user-attachments/assets/49cd0a41-5c2b-4a50-a492-284934c6cb13">


- [ ] Maybe a bug - in download dialog, the orange warning dialog shouldn't appear by default unless user has (1) selected "Download tomogram" and (2) selected a non-standard tomogram <img width="501" alt="Screenshot 2024-09-20 at 9 37 02 AM" src="https://github.com/user-attachments/assets/165b97e6-2ddf-4332-bc23-914603a40619">

2024-09-20 17:25 UTC, bchu1 commented
> thanks @bchu1, this is looking so good!
> 
> **Here's my comments based on the video:**
> 
> * [x]  Seem to be missing the space between the empty state description and the folder illustrations -- should be space-xxl in between
> 
> <img alt="Screenshot 2024-09-20 at 9 28 23 AM" width="592" src="https://private-user-images.githubusercontent.com/63013360/369481187-083684f4-5f4b-44a8-b3cb-1173ca89ac1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTMzNzcsIm5iZiI6MTcyNjg1MzA3NywicGF0aCI6Ii82MzAxMzM2MC8zNjk0ODExODctMDgzNjg0ZjQtNWY0Yi00NGE4LWIzY2ItMTE3M2NhODlhYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNzgxMTYzOGRiNGUyNjc1MWE2NzY0YjRlZjJhOWVkYmMyNDhhODZlODFiZjc3OWVkYzM2MzFhN2E1N2ExMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LxxxT8sKCuWstUixnxaxWXRuN8UT_wVgH7Jz3h0pIhU">
> **These two relate to the download run data dialog, so this may not be the right ticket to fix this feedback in:**
> 
> * [ ]  Low priority - In download dialog, can we have the "Download all run data" callout default to open? (seems SDS v2 fixed the bug where it was stuck open, but open is preferred) <img alt="Screenshot 2024-09-20 at 9 33 42 AM" width="505" src="https://private-user-images.githubusercontent.com/63013360/369483914-49cd0a41-5c2b-4a50-a492-284934c6cb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTMzNzcsIm5iZiI6MTcyNjg1MzA3NywicGF0aCI6Ii82MzAxMzM2MC8zNjk0ODM5MTQtNDljZDBhNDEtNWMyYi00YTUwLWE0OTItMjg0OTM0YzZjYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYjk3ZmMzY2NmMGIzNWFmN2Y3NDI3NGFlNjk1MjdmZDhjNTU3ZDhhNGZmMjJiNTIxMjE1N2M5NmQ0NjVkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dETik1ezX97VWjE4pm4npQE6R5crKcjQq_dX3Up4M7A">
> * [ ]  Maybe a bug - in download dialog, the orange warning dialog shouldn't appear by default unless user has (1) selected "Download tomogram" and (2) selected a non-standard tomogram <img alt="Screenshot 2024-09-20 at 9 37 02 AM" width="501" src="https://private-user-images.githubusercontent.com/63013360/369483158-165b97e6-2ddf-4332-bc23-914603a40619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTMzNzcsIm5iZiI6MTcyNjg1MzA3NywicGF0aCI6Ii82MzAxMzM2MC8zNjk0ODMxNTgtMTY1Yjk3ZTYtMmRkZi00MzMyLWJjMjMtOTE0NjAzYTQwNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZmY3OGY4MGFhOGMwNmY4ZDk2M2RjMGEzOThhNmU2YzEwNGUyNzNkZWUzZWZhNTcxY2JhYmY3ODE4NzgyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQ5xTwDpU2ufSAIIBNpQFYC1TuecxQLc8_iA_OqPKa4">

Gap added:
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/b94cee21-5602-4fa8-9663-02ddb4827bc3">

The other 2 will be done separately

2024-09-20 17:26 UTC, Janeece approved these changes
LGTM thank you @bchu1

2024-09-23 23:17 UTC, ehoops-cz approved these changes

2024-09-23 23:33 UTC, merged