docs: update docs header
chanzuckerberg/cryoet-data-portal pull request #826
Opened 2024-06-24 19:37 UTC by codemonkey800

#570

Updates the docs header to match the new design

## Demo

https://cryoet-docs-header.vercel.app/

<img width="1728" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/9a26c29f-4e47-4203-9e42-3ab0bdcfa975">

2024-06-24 21:14 UTC, kne42 approved these changes

2024-06-24 21:41 UTC, Janeece requested changes
Overall lgtm, but i have 2 recommendations on the logo divider's color and spacing

2024-06-24 21:41 UTC, Janeece commented on docs/_templates/layout.html
> +              <div style="width: 1px; height: 16px; background: #fff; margin: 0 16px"></div>
@codemonkey800 i think the divider's left & right margins are too large & too bright, can we:

- reduce left/right margin to 4px
- change "background" color to #999

2024-06-25 20:12 UTC, Janeece approved these changes
@codemonkey800 LGTM thanks!

2024-06-26 19:14 UTC, merged